AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  A microservice to generate waveforms

  Check out https://github.com/firstcoders/stems-player-documentation/wiki
  for more information.

Conditions:
  CreateBucket: !Not [!Equals [!Ref ExistingBucket, true]]

Parameters:
  # todo more validation
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
  LogLevel:
    Type: String
    Description: The log level
    Default: 'error'
    AllowedValues:
      - debug
      - info
      - error
  StageName:
    Type: String
    Description: The api gateway stage name
    Default: 'prd'
  BucketName:
    Type: String
    Description: The bucket where to store the waveform data cache
  ExistingBucket:
    Type: String
    Description: Whether to create the waveform bucket
    AllowedValues:
      - true
      - false
    Default: false
  CORSAllowedOrigins:
    Type: String
    Description: The allowed origin header value to return
    Default: ''
  AudiowaveformLayerArn:
    Type: String
    Description: The arn of the lambda layer containing audiowaveform static binaries
  AllowedAudioOrigins:
    Type: CommaDelimitedList
    Description: Comma-delimited list of origins from which the service can fetch audio
    Default: '*'
  AuthorizerArn:
    Type: String
    Description: The ARN of a lambda authorizer
  S3FolderPrefix:
    Type: String
    Description: A prefix under which the generated files will be stored
    Default: 'waveform-srv'

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    CodeUri: src
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel
        WAVEFORM_BUCKET_NAME: !Ref BucketName
        CORS_ALLOWED_ORIGINS: !Ref CORSAllowedOrigins
        AUDIOWAVEFORM_BIN_PAH: /opt/bin/audiowaveform
        ALLOWED_AUDIO_ORIGINS: !Join [',', !Ref AllowedAudioOrigins]
        S3_FOLDER_PREFIX: !Ref S3FolderPrefix

Resources:
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      EndpointConfiguration:
        Type: REGIONAL
      # https://github.com/aws/serverless-application-model/releases/tag/v1.46.0
      # https://github.com/aws/serverless-application-model/pull/2298
      ApiKeySourceType: AUTHORIZER
      Auth:
        DefaultAuthorizer: BearerTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BearerTokenAuthorizer:
            FunctionArn: !Ref AuthorizerArn
            ReauthorizeEvery: 300
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'86400'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'*'"
              Access-Control-Allow-Origin: "'*'"

  GetWaveformFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Gets waveform data based on a audio file provided by a URL
      Handler: handlers/getWaveform.handler
      Layers:
        - !Ref AudiowaveformLayerArn
      Events:
        GetWaveform:
          Type: Api
          Properties:
            RestApiId: !Ref ServiceApi
            Path: /waveform
            Method: get
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        OutExtension:
          - .js=.mjs
        Target: 'es2020'
        Sourcemap: false
        EntryPoints:
          - handlers/getWaveform.js
        External:
          - '@aws-sdk'
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  WaveformBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: CreateBucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  ApiId:
    Description: 'The API Gateway id'
    Value: !Ref ServiceApi
  ServiceApi:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/'
  ServiceDomain:
    Description: 'API Gateway domain'
    Value: !Sub '${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com'
  GetWaveformFunctionArn:
    Description: The ARN of the getwaveform function
    Value: !GetAtt GetWaveformFunction.Arn
  GetWaveformFunctionRoleArn:
    Description: The ARN of the getwaveform function role
    Value: !GetAtt GetWaveformFunctionRole.Arn

Metadata:
  AWS::ServerlessRepo::Application:
    Name: fc-audio-waveform-service
    Description: >
      A serverless microservice to generate waveforms based on a audio file provided by a URL
    Author: Team First Coders
    ReadmeUrl: README.md
    SpdxLicenseId: AGPL-3.0-or-later
    LicenseUrl: LICENSE
    Labels: ['layer', 'lambda', 'serverless', 'waveform']
    HomePageUrl: https://github.com/firstcoders/audio-waveform-service
    SourceCodeUrl: https://github.com/firstcoders/audio-waveform-service
    SemanticVersion: 1.0.0 # overwritten by sam publish cli command
